# Generated by Django 4.0.3 on 2022-04-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.CharField(default='6:18:51 pm', max_length=225),
        ),
    ]
