# Generated by Django 4.0.3 on 2022-04-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_note_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.CharField(default='6:24:54 pm', max_length=225),
        ),
    ]
