# Generated by Django 4.0.3 on 2022-04-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_note_datestamp_alter_note_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='datestamp',
            field=models.CharField(default=None, max_length=225),
        ),
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.CharField(default=None, max_length=225),
        ),
    ]
